//! Generates `oui_generated.rs` from `data/oui_prefixes.txt` (sorted OUI → vendor),
//! optionally merged with `data/oui_overrides.txt` (same format; overrides win on duplicate).

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let data_path = Path::new(&manifest).join("data/oui_prefixes.txt");
    let override_path = Path::new(&manifest).join("data/oui_overrides.txt");
    let out_path = Path::new(&env::var("OUT_DIR").unwrap()).join("oui_generated.rs");

    let mut map: BTreeMap<[u8; 3], String> = BTreeMap::new();
    load_oui_into_map(&data_path, &mut map);
    if override_path.exists() {
        load_oui_into_map(&override_path, &mut map);
    }

    let mut entries: Vec<([u8; 3], String)> = map.into_iter().collect();
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut body = String::from(
        "// @generated by build.rs — do not edit.\n\npub static OUI_LOOKUP: &[([u8; 3], &str)] = &[\n",
    );
    for (oui, name) in &entries {
        let esc = name.replace('\\', "\\\\").replace('"', "\\\"");
        body.push_str(&format!(
            "    ([0x{:02x}, 0x{:02x}, 0x{:02x}], \"{}\"),\n",
            oui[0], oui[1], oui[2], esc
        ));
    }
    body.push_str("];\n");

    fs::write(&out_path, body).expect("write oui_generated.rs");
    println!("cargo:rerun-if-changed={}", data_path.display());
    println!("cargo:rerun-if-changed={}", override_path.display());

    let ble_path = Path::new(&manifest).join("data/ble_company_ids.txt");
    let ble_out = Path::new(&env::var("OUT_DIR").unwrap()).join("ble_company_generated.rs");
    let mut ble_entries: Vec<(u16, String)> = Vec::new();
    if ble_path.exists() {
        let text = fs::read_to_string(&ble_path).unwrap_or_default();
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let Some((id_s, vendor)) = line.split_once('\t') else {
                continue;
            };
            let id_s = id_s.trim().replace("0x", "");
            let Ok(id) = u16::from_str_radix(&id_s, 16) else {
                continue;
            };
            let vendor = vendor.trim();
            if vendor.is_empty() {
                continue;
            }
            ble_entries.push((id, vendor.to_string()));
        }
    }
    ble_entries.sort_by(|a, b| a.0.cmp(&b.0));
    ble_entries.dedup_by(|a, b| a.0 == b.0);

    let mut ble_body = String::from(
        "// @generated by build.rs — do not edit.\n\npub static BLE_COMPANY_LOOKUP: &[(u16, &str)] = &[\n",
    );
    for (id, name) in &ble_entries {
        let esc = name.replace('\\', "\\\\").replace('"', "\\\"");
        ble_body.push_str(&format!("    (0x{:04x}, \"{}\"),\n", id, esc));
    }
    ble_body.push_str("];\n");
    fs::write(&ble_out, ble_body).expect("write ble_company_generated.rs");
    println!("cargo:rerun-if-changed={}", ble_path.display());
}

fn load_oui_into_map(path: &Path, map: &mut BTreeMap<[u8; 3], String>) {
    if !path.exists() {
        return;
    }
    let text = fs::read_to_string(path).unwrap_or_default();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((prefix, vendor)) = line.split_once('\t') else {
            continue;
        };
        let prefix = prefix.trim();
        let vendor = vendor.trim();
        if vendor.is_empty() {
            continue;
        }
        if let Some(oui) = parse_oui_prefix(prefix) {
            map.insert(oui, vendor.to_string());
        }
    }
}

fn parse_oui_prefix(s: &str) -> Option<[u8; 3]> {
    let s = s.replace(':', "");
    if s.len() != 6 {
        return None;
    }
    let b = u32::from_str_radix(&s, 16).ok()?;
    Some([
        ((b >> 16) & 0xff) as u8,
        ((b >> 8) & 0xff) as u8,
        (b & 0xff) as u8,
    ])
}
